### ISSUE TITLE
Watch Trailer Button

### ISSUE THREAD

**Issue by Nakisa-Alipour** [Nakisa-Alipour/frontend-project-one#3]
# Watch Trailer Button

## User Story
As a movie enthusiast, 
I want to have an app that provides information about movies,
so that I can easily find new movies to watch.

## Acceptance Criteria
GIVEN a movie suggestion app
WHEN I find a movie that interests me and click on on "watch trailer" button, 
THEN I should be able to watch its trailer.
WHEN I use app to watch a movie trailer,
THEN the app should utilize the Youtube API as a server-side API.

**Comment by SadimaMaharjan** [comment]
The watch trailer functionality has been added.
